name: Deploy on EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

concurrency:
  group: cd-ec2-${{ github.ref }}
  cancel-in-progress: true

env:
  EC2_PATH: /opt/app
  SSH_PORT: 22

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Trust EC2 host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${EC2_PORT:-${SSH_PORT}} -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: Rsync project to EC2
        run: |
          RSYNC_RSH="ssh -p ${EC2_PORT:-${SSH_PORT}}"
          rsync -az --delete \
            --exclude '.git' --exclude '.github' \
            --exclude '__pycache__' --exclude '.venv' \
            ./ "${{ secrets.EC2_USER }}"@"${{ secrets.EC2_HOST }}":"$EC2_PATH"

      - name: Build & restart with Compose on EC2
        run: |
          ssh -p ${EC2_PORT:-${SSH_PORT}} "${{ secrets.EC2_USER }}"@"${{ secrets.EC2_HOST }}" bash -lc '
            set -euo pipefail
            cd "$EC2_PATH"
            docker compose pull || true         # in case some services use images
            docker compose build                # build images defined by Dockerfiles
            docker compose up -d                # recreate only if needed
            docker compose ps
          '
